apiVersion: apps/v1
kind: Deployment # The kind of object we want to create
metadata: # Data that helps uniquely identify the object
  name: react-app-deployment
spec: # Set the desired state of our deployment
  replicas: 3 # Number of the pods
  selector:
    matchLabels:
      app: react-app-label
  template:
    metadata:
      labels:
        app: react-app-label
    spec: # Desired state of the pod
      containers:
      - name: react-app-container
        image: soukaina915/ai-front:latest
        ports:
        - containerPort: 80 # The number of ports to expose on the pod ip address
